title: Travis Whitfield
description: Personal site and project portfolio
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

author:
  name: Travis Whitfield

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: single
